# .scrutinizer.yml
filter:
    excluded_paths:
        - tests/*
        - vendor/*
        - bin/*
        - i18n/*
tools:
    php_code_sniffer:
        config:
            standard: "WordPress"
checks:
    php:
        code_rating: true
        duplication: true
