notifications:
  email: false
language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.3 WP_MULTISITE=0
- WP_VERSION=4.2 WP_MULTISITE=0
git:
  submodules: false
before_script:
- composer self-update
- composer install
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
before_deploy:
- composer self-update
- composer install
- npm install
- grunt
deploy:
  provider: releases
  file: build/adpress/adpress-plugin.zip
  skip_cleanup: true
  api-key:
    secure: My65uOM0aeHbWQTwj8TcsAelF7ni/X39KSkfBksJfJkvXX6lNruuBOeu1AplaLsNZ4U6Zhoygnh9upIk22MxbfNNXjO+eCzGruXismPb1XQTlARaNoril1QJdh7x3/6MsWWfNGLq1j4fEN7Xoub9gsIG4esV8AjXm+cxvTLWDsyWfsSOjOrUy47vSoWmqNZKljibRy5Ff29G7pMzqv2FGKPN9YUiDfaLAZgrCUQT0L4miFHRagFvPvWBe22zXwArPTfn6iKYwAHyXRgLLwXvjVCfYiy7P2LuCJbkcGgDMLQZg4RmXG6kxenAhvdrins8BnnyeGVdyZiiFMbvLBTraEhm9moN7FLzO2hnM0fmZoc4dNXzgd1KG0A9UlPCmM4ERz7xPGBpF7LDu0jGxyaeJhnvUlOWbCOIp/mk5jwPaR0DCWEmCJBoqlOa6qgmWJ7j7IzC3Yr2yGaoM7tDnBy9pG4XCoNTOBdJcE6Phm/OJalZ0Abw+alW+0tAYkaWKrV3aTG8GUaFeN+5pZVusZ2L20YehQaSswIyUKoCkPKSbGbMrYi41xQEYIOJI82NkEIYaOzpBHkW2QlGRnEx+kIERUUgIlI7+ANTyORZvN6ovSrdB1efRENgXUcq56SyVhmbAQz3YNNroJ48pOwecDpSrdU9VynTc4oPpfR04x0BvAM=
  on:
    tags: true
